Project/routes/admin.php
<?php

    Route::GET('/home', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');
    Route::get('/me', 'AdminController@me')->name('admin.me');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    // active status
    Route::post('activation/{admin}', 'ActivationController@activate')->name('admin.activation');
    Route::delete('activation/{admin}', 'ActivationController@deactivate');
    Route::resource('permission', 'PermissionController');

    Route::fallback(function () {
        return abort(404);
    });

Project/routes/web.php
<?php

use Faker\Factory;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['before' => 'auth','prefix' => '/admin','as'=>'admin.' , 'namespace' => 'Admin'], function () {
	Route::get('/' , 'DashboardController@index')->name('dashboard');
	Route::resource('categories' , 'CategoryController');
	Route::resource('properties' , 'PropertyController');
});




Route::get('/', 'HomeController@index')->name('home');


Auth::routes(['verify' => false]);


Route::name('profile.')->middleware(['auth'])->prefix('profile')->group(function (){
    Route::get('/' , 'App\UserController@profileIndex')->name('index');
    Route::patch('/avatar/update' , 'App\UserController@avatarUpdate')->name('avatar.update');
    Route::get('/edit' , 'App\UserController@edit')->name('edit');
    Route::patch('/edit/update' , 'App\UserController@updateUser')->name('updateUser');
    Route::get('/info' , 'App\UserController@profileInfo')->name('info');
    Route::resource('address' , 'App\AddressController');
    Route::get('orders' , 'App\UserOrderController@index')->name('orders');
    Route::get('wishlist' , 'App\WishListController@index')->name('wishlist');
    Route::get('like/{product}','App\UserController@ProductLiked')->name('like');
    Route::get('password' , 'App\UserController@showChangePassword')->name('change.password');
    Route::resource('store' , 'App\StoreController')->only(['create','show']);
});









Route::get('/test' , function (){

});

Project/resources/views/Sections/App/Footer.blade.php
<!-- row-footer -->
<div class="top-footer text-center">
    <img src="/images/footer.svg" alt="">
</div>
<footer class="container-fluid row-footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-6 col-lg-4 order-1 order-lg-1">
                <div class="title-products">
                    <h3 class="pro-title fs-18 dastnevis header-gradient text-center d-inline-block px-3 px-md-5 mb-0">دسترسی سریع</h3>
                    <hr class="under-title">
                </div>
                <div class="content-footer p-3 pt-4 bg-ff bx-sh text-right">
                    <ul class="footer-menu">
                        <li class="d-block">
                            <a href="/#">همکاری با هنرچی</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">درباره هنرچی</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">تماس با ما</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">سوالات متداول</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">قوانین و مقررات</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">لیست گالری ها</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">وبلاگ</a>
                        </li>
                        <li class="d-block">
                            <a href="/#">ثبت شکایات</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-12 col-lg-4 order-3 order-lg-2 mt-5">
                <div class="title-products">
                    <h3 class="pro-title fs-18 dastnevis header-gradient text-center d-inline-block px-3 px-md-5 mb-0">عضویت در خبرنامه</h3>
                    <hr class="under-title">
                </div>
                <div class="content-footer-1 text-right">
                    <div class="form-group bmd-form-group news">
                        <input type="email" class="form-control bg-input" placeholder="sample@gmail.com">
                    </div>
                </div>
                <button class="btn btn-info btn-round btn-circle circle-1 position-relative fs-16 dastnevis py-2">
                    <i class="fal fa-paper-plane clr-info fs-20 position-relative"></i>
                    عضویت در خبرنامه
                </button>
                <div class="area-logoes text-center mt-4 p-3 bx-sh">
                    <a href="/#"><img class="d-inline-block" src="/images/accessory/namad01.png" alt=""></a>
                    <a href="/#"><img class="d-inline-block" src="/images/accessory/namad02.png" alt=""></a>
                    <a href="/#"><img class="d-inline-block" src="/images/accessory/namad03.png" alt=""></a>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-4 order-2 order-lg-3">
                <div class="title-products">
                    <h3 class="pro-title fs-18 dastnevis header-gradient text-center d-inline-block px-3 px-md-5 mb-0">تماس با ما</h3>
                    <hr class="under-title">
                </div>
                <div class="content-footer p-3 pt-4 bg-ff bx-sh text-right">
                    <div class="contact-us py-2">
                        <i class="fal fa-map-marker-alt fs-25 clr-blue2 ml-2"></i>
                        <span class="fs-14">تهران، اقدسیه، میدان ازگل، کوچه نوبهار</span>
                    </div>
                    <div class="contact-us py-2">
                        <i class="fal fa-mobile-alt fs-25 clr-blue2 ml-2"></i>
                        <span class="fs-14">09120760113</span>
                    </div>
                    <div class="contact-us py-2">
                        <i class="fal fa-phone-office fs-25 clr-blue2 ml-2"></i>
                        <span class="fs-14">056 32210006</span>
                    </div>
                    <div class="contact-us py-2">
                        <i class="fal fa-envelope fs-25 clr-blue2 ml-2"></i>
                        <span class="fs-14">info@viranika.com</span>
                    </div>
                    <div class="social-network text-center">
                        <div class="area-so d-inline-block bg-ff">
                            <a href="/#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </div>
                        <div class="area-so d-inline-block bg-ff">
                            <a href="/#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </div>
                        <div class="area-so d-inline-block bg-ff">
                            <a href="/#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </div>
                        <div class="area-so d-inline-block bg-ff">
                            <a href="/#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                        <div class="area-so d-inline-block bg-ff">
                            <a href="/#">
                                <i class="fal fa-paper-plane"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<section class="container-fluid copyright py-4 bg-cc">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 text-center text-lg-right">
                <p class="m-0 mt-1 dastnevis fs-16">تمامی حقوق کپی رایت نزد سایت
                    <a class="clr-42" href="/#">هنرچی</a>
                    محفوظ است.
                </p>
            </div>
            <div class="col-lg-6 text-center text-lg-left mt-3 mt-lg-0">
                <p class="d-inline-block m-0 dastnevis fs-16">طراحی و توسعه توسط تجارت نوین</p>
                <a href="/#"><img src="/http://viranika.com/wp-content/uploads/2018/11/logo-w.svg" alt=""></a>
            </div>
        </div>
    </div>
</section>

Project/resources/views/Sections/App/Header.blade.php
<!-- Start Header -->
<section class="container-fluid top-bar"></section>
<section class="container-fluid top-header bg-ff">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3 logo-area">
                <a href="/#">
                    <img src="/images/logo.svg" alt="هنرچی">
                </a>
            </div>
            <div class="col-12 col-md-8 col-lg-9 user-menu text-center text-md-left text-lg-left">
                <ul class="user-menu-ul">
                    <li id="search-form" class="search-form w-50">
                        <div class="input-group ">
                            <input type="search" class="form-control" placeholder="محصول موردنظرت رو پیدا کن...">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                     <i class="fal fa-search"></i>
                                </span>
                            </div>
                        </div>
                    </li>
                    <li id="profile" class="profile">
                        <a class="profile-link" href="{{route('profile.index')}}">
                            <i class="fal fa-user"></i>
                        </a>
                        @auth()
                        <!-- is-login -->
                        <ul class="tooltip-profile cart-tooltip p-2">
                            <li class="d-block text-right mb-1">
                                <a class="d-block" href="{{route('profile.index')}}">
                                    <i class="fal fa-user ml-2 "></i>
                                    پروفایل
                                </a>
                            </li>
                            <li class="d-block text-right mb-1">
                                <a class="d-block" href="{{route('profile.orders')}}">
                                    <i class="fal fa-shopping-basket ml-2"></i>
                                    سفارش های من
                                </a>
                            </li>
                            <li class="d-block text-right  mb-1">
                                <form action="{{route('logout')}}" method="post">
                                    @csrf
                                    <button type="submit" style="display: contents; text-align: right">
                                        <a class="d-block" href="#">
                                            <i class="fal fa-sign-out ml-2">
                                            </i>
                                            <d>
                                                خروج از حساب کاربری
                                            </d>
                                        </a>
                                    </button>
                                </form>

                            </li>
                        </ul>
                        @endauth
                        @guest()
                        <ul class="tooltip-profile cart-tooltip p-2">
                            <div class="login-link text-center">
                                <a href="{{ route('login') }}">
                                    <button class="btn btn-primary btn-round">
                                        <i class="fal fa-sign-in ml-2"></i>
                                        ورود به هنرچی
                                    </button>
                                </a>
                            </div>
                            <br>
                            <hr>
                            <div class="register-link text-center mt-2">
                                <p>کاربر جدید هستید ؟
                                    <a class="clr-blue2" href="{{route('register')}}">ثبت نام</a>
                                </p>
                            </div>
                        </ul>
                        @endguest
                    </li>
                    <li id="wishlist" class="wishlist">
                        <a class="wishlist-link" href="/#">
                            <i class="fal fa-heart"></i>
                        </a>
                    </li>
                    <li id="heder-cart" class="header-cart">
                        <a class="p-0 mr-2 header-cart-link" href="#">
                            <div class="cart-count-area">
                                <span class="cart-count">0</span>
                            </div>
                            <i class="fal fa-shopping-cart"></i>
                        </a>
                        @include('Components.App.HeaderCart')
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </div>
</section>
@include('Components.App.NavigationBar')
<section class="container-fluid svg-bg p-0">
    <div class="svg-area">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
             viewBox="0 0 500 31.5" style="enable-background:new 0 0 500 31.5;" xml:space="preserve">
			<style type="text/css">
                .st0{opacity:0.33;fill:#F5F5F5;enable-background:new    ;}
                .st1{opacity:0.66;fill:#F5F5F5;enable-background:new    ;}
                .st2{fill:#F5F5F5;}
            </style>
            <path class="st0" d="M236.5,21.2c-101.9,27.7-131.6-10.6-160.1,0C33,37.4,0,18.8,0,18.8V0.1h500v18.7c0,0-31,8.2-47.5,9.2
				c-16.4,1-31.4-3.9-37.9-6.9c-11.6-5.4-42-18.2-67.2-19.5S246.2,18.6,236.5,21.2z"/>
            <path class="st1" d="M367,21.2c-22.8,0-38.6-7.3-64.5-12.2c-14.3-2.7-75.1-3.2-127,12.2s-45.9-10.8-74.6,0C57.8,37.2,0,12.6,0,12.6
				V0.1h500v11.4c0,0-14.1-5.8-46-5.8C405.1,5.8,387.9,21.2,367,21.2z"/>
            <path class="st2" d="M383,9.2c-100-18-133,20.5-197.6,6.1C121,0.7,121,1.8,92.4,6.6C64,11.3,66.2,14.2,45,16.6
			C14.3,20.1,0,0.1,0,0.1h500c0,0-5,12.8-41.8,15.1S414.8,14.8,383,9.2z"/>
		</svg>

    </div>
</section>
<!-- End Header -->