Project/routes/admin.php
<?php

    Route::GET('/home', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');
    Route::get('/me', 'AdminController@me')->name('admin.me');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    // active status
    Route::post('activation/{admin}', 'ActivationController@activate')->name('admin.activation');
    Route::delete('activation/{admin}', 'ActivationController@deactivate');
    Route::resource('permission', 'PermissionController');

    Route::fallback(function () {
        return abort(404);
    });

Project/routes/web.php
<?php

use Faker\Factory;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['before' => 'auth','prefix' => '/admin','as'=>'admin.' , 'namespace' => 'Admin'], function () {
	Route::get('/' , 'DashboardController@index')->name('dashboard');
	Route::resource('categories' , 'CategoryController');
	Route::resource('properties' , 'PropertyController');
});




Route::get('/', 'HomeController@index')->name('home');


Auth::routes(['verify' => false]);


Route::name('profile.')->middleware(['auth'])->prefix('profile')->group(function (){
    Route::get('/' , 'App\UserController@profileIndex')->name('index');
    Route::patch('/avatar/update' , 'App\UserController@avatarUpdate')->name('avatar.update');
    Route::get('/edit' , 'App\UserController@edit')->name('edit');
    Route::patch('/edit/update' , 'App\UserController@updateUser')->name('updateUser');
    Route::get('/info' , 'App\UserController@profileInfo')->name('info');
    Route::resource('address' , 'App\AddressController');
    Route::get('orders' , 'App\UserOrderController@index')->name('orders');
    Route::get('wishlist' , 'App\WishListController@index')->name('wishlist');
    Route::get('like/{product}','App\UserController@ProductLiked')->name('like');
    Route::get('password' , 'App\UserController@showChangePassword')->name('change.password');
    Route::resource('store' , 'App\StoreController')->only(['create','show']);
});









Route::get('/test' , function (){

});

Project/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\ProductCategory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
		$categories = ProductCategory::CategoriesSorted();

		return view('Admin.Categories.Index')->with("categories" , $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {

    	$categories = ProductCategory::CategoriesSorted();

        return view('Admin.Categories.Create')->with("categories" , $categories);
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return void
	 */
    public function store(Request $request)
    {
    	$request->validate([
    		'name'				=>	'required|min:4|max:30',
			'slug'				=>	'required|min:4|max:30|unique:product_categories',
			'meta-title'		=>	'required',
			'meta-keyword'		=>	'required',
			'meta-description'	=>	'required'
		]);
    	$cat = ProductCategory::create([
    		'name'				=>	$request->input('name'),
			'slug'				=>	$request->input('slug'),
			'parentId'			=>	$request->input('parentCat'),
			'metaTitle'			=>	$request->input('meta-title'),
			'metaKeyword'		=>	$request->input('meta-keyword'),
			'metaDescription'	=>	$request->input('meta-description')
		]);
    	return redirect()->route("admin.categories.index");
    }

	/**
	 * Display the specified resource.
	 *
	 * @param int $id
	 * @return void
	 */
    public function show($id)
    {
        //
    }

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param ProductCategory $category
	 * @return void
	 */
    public function edit(ProductCategory $category)
    {
		$categories = ProductCategory::CategoriesSorted();
    	return view("Admin.Categories.Edit")->with(["category" => $category , "categories" => $categories]);
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @param ProductCategory $category
	 * @return void
	 */
    public function update(Request $request, ProductCategory $category)
    {
    	$slugRol = 'required|min:4|max:30';
		($request->slug !== $category->slug)? $slugRol .='|unique:product_categories' : '';
		$request->validate([
			'name'				=>	'required|min:4|max:30',
			'slug'				=>	$slugRol,
			'meta-title'		=>	'required',
			'meta-keyword'		=>	'required',
			'meta-description'	=>	'required'
		]);

		function checkInChildes ($childes , int $id){
			if (!empty($childes)){
				foreach ($childes as $child){
					if ($child->parentId == $id){
						return false;
					}
					if ($child->Children->isNotEmpty()){
						checkInChildes($child->Children , $id);
					}
				}
			}
			return true;
		}

		$chi = checkInChildes($category->Children , $category->id);
		if ($request->input('parentCat') ==  $category->id  or $chi == false){

			return back();

		}
		$category->update([
			'name'				=>	$request->input('name'),
			'slug'				=>	$request->input('slug'),
			'parentId'			=>	$request->input('parentCat'),
			'metaTitle'			=>	$request->input('meta-title'),
			'metaKeyword'		=>	$request->input('meta-keyword'),
			'metaDescription'	=>	$request->input('meta-description')
		]);
		return redirect()->route('admin.categories.index');
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param int $id
	 * @return void
	 */
    public function destroy($id)
    {

    	$cat = ProductCategory::find($id);

    	if ($cat->Children->isNotEmpty()){
    		return back()->with("errorDelete" , "دسته مورد نظر با دسته یا محصولاتی در ارتباط است. نمیتوانید حذف نمایید.");
		}
    	$cat->delete();
        return back();
    }
}

Project/resources/views/Admin/Categories/Create.blade.php
@extends("Layouts.Admin.Admin")
@section("Content")
<?php
	function categoriesTreeView(array $cats , int $level){
		foreach ($cats as $cat){
			$option = '<option value="';
			$option .= $cat['id'].'" ';
			$option .=  ($cat['parentId'] !== null)? 'data-pup="'.$cat['parentId'].'" ':'';
			$option .= 'class="l'.$level;
			$option .= isset($cat['childes']) && is_array($cat['childes'])? ' non-leaf"' : '"';
			$option .= (old('parentCat') == $cat['id'])? 'selected >' : '>';
			$option	.= $cat['name'].'</option>';
			echo $option;
			if (isset($cat['childes']) && is_array($cat['childes'])){
				categoriesTreeView($cat['childes'] , $level+1);
			}
		}
	}
?>
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-gift"></i>افزودن دسته</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="{{route('admin.categories.store')}}" class="horizontal-form" method="post" role="form">
				@csrf
				<div class="form-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">نام دسته</label>
								<input type="text" id="name" class="form-control" name="name" placeholder="نام دسته" value="{{old('name')}}">
								<span class="help-block"></span>
							</div>
						</div>
						<!--/span-->
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">نامک</label>
								<input type="text" id="slug" class="form-control" name="slug" placeholder="نامک" value="{{old('slug')}}">
							</div>
						</div>
						<!--/span-->
					</div>
					<!--/row-->
					@if ($categories)
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">دسته مادر</label>
									<select name="parentCat" id="parentCat" class="form-control" multiple>
										<?php categoriesTreeView($categories , 1) ?>
									</select>
								</div>
							</div>
						</div>
					@endif

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="meta-title" class="control-label">متای عنوان</label>
								<input type="text" name="meta-title" id="meta-title" class="form-control" value="{{old('meta-title')}}">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="meta-keyword" class="control-label">متای کلمات کلیدی</label>
								<input type="text" name="meta-keyword" id="meta-keyword" class="form-control" value="{{old('meta-keyword')}}">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label for="meta-description" class="control-label">متای توضیحات</label>
								<textarea class="form-control" name="meta-description" id="meta-description" cols="30" rows="10">{{old('meta-description')}}</textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions right">
					<button type="submit" class="btn blue"><i
								class="fa fa-check"></i>ذخیره</button>
				</div>
			</form>
			<!-- END FORM-->
		</div>
	</div>
@endsection
@section("PagePluginsStyle")
<link rel="stylesheet" href="/AdminDashboard/plugins/select2/select2.min.css">
<link rel="stylesheet" href="/AdminDashboard/plugins/select2totree/select2totree.css">
@endsection
@section("PagePlugins")
	<script type="text/javascript" src="/AdminDashboard/plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="/AdminDashboard/plugins/select2totree/select2totree.js"></script>
@endsection

@section("PageScripts")
	<script>
		$(document).ready(function () {
			$("#parentCat").select2ToTree({
				dir:'rtl',
                maximumSelectionLength : 1
			})
        })
	</script>
@endsection

Project/resources/views/Admin/Categories/Edit.blade.php
@extends("Layouts.Admin.Admin")
@section("Content")
	<?php
	global $cat;
	$cat = $category;
	function CatData($fild){
		global $cat;
		if (old($fild) == null){
			switch ($fild){
				case 'parentCat':
					$fild = 'parentId';
					break;
				case 'meta-keyword':
					$fild = 'metaKeyword';
					break;
				case 'meta-title':
					$fild = 'metaTitle';
					break;
				case 'meta-description':
					$fild = 'metaDescription';
					break;
			}
			return $cat[$fild];
		}
		return old($fild);
	}

	function categoriesTreeView(array $cats , int $level){
		foreach ($cats as $cat){
			$option = '<option value="';
			$option .= $cat['id'].'" ';
			$option .=  ($cat['parentId'] !== null)? 'data-pup="'.$cat['parentId'].'" ':'';
			$option .= 'class="l'.$level;
			$option .= isset($cat['childes']) && is_array($cat['childes'])? ' non-leaf"' : '"';
			$option .= (CatData('parentCat') == $cat['id'])? 'selected >' : '>';
			$option	.= $cat['name'].'</option>';
			echo $option;
			if (isset($cat['childes']) && is_array($cat['childes'])){
				categoriesTreeView($cat['childes'] , $level+1);
			}
		}
	}
	?>
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-gift"></i>افزودن دسته</div>
		</div>
		<div class="portlet-body form">
			<!-- BEGIN FORM-->
			<form action="{{route('admin.categories.update' , $category)}}" class="horizontal-form" method="post" role="form">
				@csrf @method("Patch")
				<div class="form-body">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">نام دسته</label>
								<input type="text" id="name" class="form-control" name="name" placeholder="نام دسته" value="{{CatData('name')}}">
								<span class="help-block"></span>
							</div>
						</div>
						<!--/span-->
						<div class="col-md-6">
							<div class="form-group">
								<label class="control-label">نامک</label>
								<input type="text" id="slug" class="form-control" name="slug" placeholder="نامک" value="{{CatData('slug')}}">
							</div>
						</div>
						<!--/span-->
					</div>
					<!--/row-->
					@if ($categories)
						<div class="row">
							<div class="col-md-12">
								<div class="form-group">
									<label class="control-label">دسته مادر</label>
									<select name="parentCat" id="parentCat" class="form-control" multiple>
										<?php categoriesTreeView($categories , 1) ?>
									</select>
								</div>
							</div>
						</div>
					@endif

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label for="meta-title" class="control-label">متای عنوان</label>
								<input type="text" name="meta-title" id="meta-title" class="form-control" value="{{CatData('meta-title')}}">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="meta-keyword" class="control-label">متای کلمات کلیدی</label>
								<input type="text" name="meta-keyword" id="meta-keyword" class="form-control" value="{{CatData('meta-keyword')}}">
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label for="meta-description" class="control-label">متای توضیحات</label>
								<textarea class="form-control" name="meta-description" id="meta-description" cols="30" rows="10">{{CatData('meta-description')}}</textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="form-actions right">
					<button type="submit" class="btn blue"><i
								class="fa fa-check"></i>ذخیره</button>
				</div>
			</form>
			<!-- END FORM-->
		</div>
	</div>
@endsection
@section("PagePluginsStyle")
	<link rel="stylesheet" href="/AdminDashboard/plugins/select2/select2.min.css">
	<link rel="stylesheet" href="/AdminDashboard/plugins/select2totree/select2totree.css">
@endsection
@section("PagePlugins")
	<script type="text/javascript" src="/AdminDashboard/plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="/AdminDashboard/plugins/select2totree/select2totree.js"></script>
@endsection

@section("PageScripts")
	<script>
        $(document).ready(function () {
            $("#parentCat").select2ToTree({
                dir:'rtl',
                maximumSelectionLength : 1
            })
        })
	</script>
@endsection

Project/resources/views/Admin/Categories/Index.blade.php
@extends('Layouts.Admin.Admin')
@section('PagePluginsStyle')
	<link rel="stylesheet" type="text/css" href="/AdminDashboard/plugins/select2/select2.css"/>
	<link rel="stylesheet" type="text/css" href="/AdminDashboard/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css"/>
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.css"/>

@stop

@section('Content')
	<?php
	function categoriesTreeView(array $cats , int $level){
		foreach ($cats as $cat){
			?>
			<tr>
				<td><input type="checkbox" value="{{$cat['id']}}"></td>
				<td>
					@for ($i = 0; $i < $level; $i++)
						_
					@endfor
					{{$cat['name']}}
				</td>
				<td>{{$cat['slug']}}</td>
				<td>
					<form action="{{route('admin.categories.destroy' , $cat['id'] )}}" method="post">
						@csrf @method('DELETE')
						<div class="btn-group">
							<a href="{{route('admin.categories.edit' , $cat['id'] )}}" class="btn btn-success">ویرایش</a>
							<button type="submit" class="btn btn-warning">حذف</button>
						</div>

					</form>
				</td>
			</tr>

			<?php
			if (isset($cat['childes']) && is_array($cat['childes'])){
				categoriesTreeView($cat['childes'] , $level+1);
			}
		}
	}
	?>

	<div class="portlet light">
		<div class="portlet-body">
			@if (session('errorDelete'))
				<div class="alert alert-danger">
					{{	session('errorDelete') }}
				</div>
			@endif

			<table id="example" class="display" width="100%" cellspacing="0">
				<thead>
				<tr>
					<th>||</th>
					<th>نام دسته</th>
					<th>آدرس دسته</th>
					<th>عملیات</th>
				</tr>
				</thead>
				<tbody>
				<?php
				if (isset($categories)) {
					categoriesTreeView($categories , 0);
				}
				?>
				</tbody>
			</table>
		</div>
	</div>
@stop
@section('PagePlugins')

	<script type="text/javascript" src="/AdminDashboard/plugins/select2/select2.min.js"></script>
	<script type="text/javascript" src="http://vitalets.github.io/x-editable/assets/mockjax/jquery.mockjax.js"></script>

	<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.js"></script>

	<script type="text/javascript" src="/AdminDashboard/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
@stop
@section('PageScripts')

@stop