Project/routes/admin.php
<?php

    Route::GET('/home', 'AdminController@index')->name('admin.home');
    // Login and Logout
    Route::GET('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::POST('/', 'LoginController@login');
    Route::POST('/logout', 'LoginController@logout')->name('admin.logout');

    // Password Resets
    Route::POST('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::GET('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::POST('/password/reset', 'ResetPasswordController@reset');
    Route::GET('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
    Route::GET('/password/change', 'AdminController@showChangePasswordForm')->name('admin.password.change');
    Route::POST('/password/change', 'AdminController@changePassword');

    // Register Admins
    Route::get('/register', 'RegisterController@showRegistrationForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/{admin}/edit', 'RegisterController@edit')->name('admin.edit');
    Route::delete('/{admin}', 'RegisterController@destroy')->name('admin.delete');
    Route::patch('/{admin}', 'RegisterController@update')->name('admin.update');

    // Admin Lists
    Route::get('/show', 'AdminController@show')->name('admin.show');
    Route::get('/me', 'AdminController@me')->name('admin.me');

    // Admin Roles
    Route::post('/{admin}/role/{role}', 'AdminRoleController@attach')->name('admin.attach.roles');
    Route::delete('/{admin}/role/{role}', 'AdminRoleController@detach');

    // Roles
    Route::get('/roles', 'RoleController@index')->name('admin.roles');
    Route::get('/role/create', 'RoleController@create')->name('admin.role.create');
    Route::post('/role/store', 'RoleController@store')->name('admin.role.store');
    Route::delete('/role/{role}', 'RoleController@destroy')->name('admin.role.delete');
    Route::get('/role/{role}/edit', 'RoleController@edit')->name('admin.role.edit');
    Route::patch('/role/{role}', 'RoleController@update')->name('admin.role.update');

    // active status
    Route::post('activation/{admin}', 'ActivationController@activate')->name('admin.activation');
    Route::delete('activation/{admin}', 'ActivationController@deactivate');
    Route::resource('permission', 'PermissionController');

    Route::fallback(function () {
        return abort(404);
    });

Project/routes/web.php
<?php

use Faker\Factory;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['before' => 'auth','prefix' => '/admin','as'=>'admin.' , 'namespace' => 'Admin'], function () {
	Route::get('/' , 'DashboardController@index')->name('dashboard');
	Route::resource('categories' , 'CategoryController');
	Route::resource('properties' , 'PropertyController');
});




Route::get('/', 'HomeController@index')->name('home');


Auth::routes(['verify' => false]);


Route::name('profile.')->middleware(['auth'])->prefix('profile')->group(function (){
    Route::get('/' , 'App\UserController@profileIndex')->name('index');
    Route::patch('/avatar/update' , 'App\UserController@avatarUpdate')->name('avatar.update');
    Route::get('/edit' , 'App\UserController@edit')->name('edit');
    Route::patch('/edit/update' , 'App\UserController@updateUser')->name('updateUser');
    Route::get('/info' , 'App\UserController@profileInfo')->name('info');
    Route::resource('address' , 'App\AddressController');
    Route::get('orders' , 'App\UserOrderController@index')->name('orders');
    Route::get('wishlist' , 'App\WishListController@index')->name('wishlist');
    Route::get('like/{product}','App\UserController@ProductLiked')->name('like');
    Route::get('password' , 'App\UserController@showChangePassword')->name('change.password');
    Route::resource('store' , 'App\StoreController')->only(['create','show']);
});









Route::get('/test' , function (){

});

Project/resources/views/App/Profile/Address.blade.php
<?php
$user = Auth::user();
function userData(string $filed)
{
	$user = Auth::user();
	if (old($filed) == null) {
		return $user->$filed;
	}
	return old($filed);
}

?>
@extends('Layouts.App.Profile')
@section('profile-content')

	<div class="profile-box">
		<div class="title-products text-right">
			<h3 class="pro-title fs-18 dastnevis header-gradient d-inline-block px-4 px-md-4 mb-0 mt-0 pb-2">آدرس ها</h3>
			<hr class="under-title">
		</div>
		<div class="pbox bg-ff bx-sh px-3 py-3">
			@foreach($addresses as $address)
				<div class="address_body">
					<div class="row text-right">
						<div class="col-lg-12 col-md-12 col-sm-12 my-1">
							گیرنده:<span class="fs-16 m-0 address_receiver">{{$address->receiver}}</span>
						</div>

						<div class="col-lg-12 col-md-12 col-sm-12 my-1">
                            <span class="address_state">{{ $address->state}}</span> -
                            <span class="address_city">{{ $address->city}}</span>
							<p class="fs-16 m-0 address_detail">{{$address->city}}<br>{{$address->address}}</p>
						</div>
					</div>
					<div class="ab-hr d-none d-lg-block"></div>
					<div class="col-lg-12 col-md-12 col-sm-12 my-2">
						<i class="fal fa-barcode-read fs-20 d-inline-block"></i>
						<p class="fs-14 m-0 mr-2 d-inline-block">کد پستی :</p>
						<p class="fs-14 m-0 mr-2 d-inline-block address_post_code">{{$address->postCode}}</p>
					</div>
					<div class="col-lg-12 col-md-12 col-sm-12 my-2">
						<i class="fal fa-mobile-alt fs-25 mr-1 d-inline-block"></i>
						<p class="fs-14 m-0 mr-2 d-inline-block">تلفن همراه :</p>
						<p class="fs-14 m-0 mr-2 d-inline-block address_mobile">{{$address->mobile}}</p>
					</div>
					<div class="text-left">
						<a class="editAddressAjax" href="javascript:;" editUrl="{{route('profile.address.edit',['address'=>$address->id])}}">
							<button class="btn pro-frm-btn">
								ویرایش
							</button>
						</a>
						<form action="{{route('profile.address.destroy',['address'=>$address->id])}}" method="post" style="display: contents">
							@csrf
							{{method_field('DELETE')}}
							<a>
								<button class="btn pro-frm-btn">حذف</button>
							</a>
						</form>


					</div>
				</div>
			@endforeach
		</div>

	</div>
	<button class="btn btn-round add-address-btn p-4 my-4 clr-75 fs-18" data-toggle="modal" data-target="#add-address">
		<i class="fal fa-map-marker-plus d-block my-1"></i>
		افزودن آدرس جدید
	</button>
	<div class="modal fade" id="add-address" tabindex="-1" role="">
		<div class="modal-dialog modal-login modal-lg" role="document">
			<div class="modal-content">
				<div class="card card-signup card-plain">
					<div class="modal-header">
						<button type="button" class="close mt-0" data-dismiss="modal" aria-label="Close">
							<i class="fal fa-times"></i>
						</button>
					</div>
					<div class="modal-body">
						<form class="form" method="post" action="{{route('profile.address.store')}}" enctype="multipart/form-data">
							@csrf
							<p class="text-center">
								<img src="images/logo.svg" alt="هنرچی" style="width: 250px;">
							</p>
							<div class="card-body text-right">
								<div class="col-lg-12 col-md-12 col-sm-12 my-2">
									<i class="fal fa-map-marked-alt fs-20 d-inline-block"></i>
									<p class="fs-14 m-0 mr-2 d-inline-block">افزودن آدرس جدید</p>
								</div>

								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-user"></i>
											</div>
										</div>
										<input type="text" name="receiver" class="form-control @error('receiver') is-invalid @enderror" value="{{old('receiver')}}" placeholder="نام و نام خانوادگی گیرنده">
										@error('receiver')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-mobile-alt"></i>
											</div>
										</div>
										<input type="text" name="mobile" class="form-control @error('mobile') is-invalid @enderror" value="{{old('mobile')}}" placeholder="شماره همراه">
										@error('mobile')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-mobile-alt"></i>
											</div>
										</div>
										<input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{old('phone')}}" placeholder="تلفن ثابت">
										@error('phone')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-map-marker-alt"></i>
											</div>
										</div>
										<input type="text" name="state" class="form-control @error('state') is-invalid @enderror" value="{{old('state')}}" placeholder="استان">
										@error('state')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-map-marked"></i>
											</div>
										</div>
										<input type="text" name="city" class="form-control @error('city') is-invalid @enderror" value="{{old('city')}}" placeholder="شهر">
										@error('city')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-street-view"></i>
											</div>
										</div>
										<input type="text" name="address" class="form-control @error('address') is-invalid @enderror" value="{{old('address')}}" placeholder="آدرس گیرنده">
										@error('address')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-barcode-read"></i>
											</div>
										</div>
										<input type="text" name="postCode" class="form-control @error('postCode') is-invalid @enderror" value="{{old('postCode')}}" placeholder="کد پستی">
										@error('postCode')
										<span class="invalid-feedback" role="alert" style="text-align: right">
                                            <strong>{{ $message }}</strong>
                                        </span>
										@enderror
                                    </div>
								</div>
								<div class="form-group bmd-form-group">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text">
												<i class="fal fa-text-width" style="margin-bottom: auto;margin-top: 5px"></i>
											</div>
										</div>
										<textarea class="form-control" name="description" rows="3" placeholder="توضیحات اضافه" id="des"></textarea>
									</div>
								</div>
							</div>
							<div class="modal-footer justify-content-center">
								<button type="submit" class="btn pro-frm-btn px-4">ثبت آدرس</button>
							</div>
						</form>
					</div>

				</div>
			</div>
		</div>
	</div>







@endsection
@section('pageScript')
	<script>
        var currentEdit;
        var createAddress = $("#add-address form").clone();
        var ajaxPost = function (f) {
            $.post(f.attr("action"), f.serialize(), function (data) {
                let formData = new FormData($(f)[0]);
                $("#add-address .modal-body").empty();
                let form = $(data)[0];
                if (data === 'Ok') {
                    currentEdit.find(".address_receiver").text(formData.get('receiver'));
                    currentEdit.find(".address_state").text(formData.get('state'));
                    currentEdit.find(".address_city").text(formData.get('city'));
                    currentEdit.find(".address_detail").text(formData.get('address'));
                    currentEdit.find(".address_mobile").text(formData.get('mobile'));
                    currentEdit.find(".address_post_code").text(formData.get('postCode'));
                    $("#add-address div.modal-header > button").click();
                    $("#add-address .modal-body").append(createAddress);
                } else {
                    $("#add-address .modal-body").html(form);
                }


            })
        };
        $(document).ready(function () {
            $(".editAddressAjax").on("click", function () {
                let url = $(this).attr('editUrl');
                currentEdit = $(this).closest("div.address_body")
                let xhttp = new XMLHttpRequest();
                xhttp.onreadystatechange = function () {
                    if (this.readyState == 4 && this.status == 200) {
                        $("#add-address .modal-body").empty();
                        let form = $(this.responseText)[0];
                        $("#add-address .modal-body").html(form);
                        $("body > section.container-fluid.profile-page > div > div > div.col-lg-9.col-md-8.mt-2.p-left > button").click();
                        $("#add-address form").on("submit", function (e) {
                            e.preventDefault();
                            ajaxPost($(form))
                        })
                    }
                };
                xhttp.open('GET', url, true);
                xhttp.send();
            });

            $("#add-address form").on("submit", function (e) {
                e.preventDefault();
            })
        })
	</script>
@endsection

Project/resources/views/App/Profile/EditAddress.blade.php
@php
	function data($filed , $data , $address){
		if (!array_key_exists($filed, $data))
			{
				return $address->$filed;
			}
		return $data[$filed];
	}
@endphp


<form class="form" method="post" action="{{ $route }}" enctype="multipart/form-data">
	@csrf
	@isset($method)
		@method($method)
	@endisset
	<p class="text-center">
		<img src="images/logo.svg" alt="هنرچی" style="width: 250px;">
	</p>
	<div class="card-body text-right">
		<div class="col-lg-12 col-md-12 col-sm-12 my-2">
			<i class="fal fa-map-marked-alt fs-20 d-inline-block"></i>
			<p class="fs-14 m-0 mr-2 d-inline-block">ویرایش آدرس</p>
		</div>

		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-user"></i>
					</div>
				</div>
				<input type="text" name="receiver" class="form-control @error('receiver') is-invalid @enderror" value="{{data('receiver', $data , $address)}}" placeholder="نام و نام خانوادگی گیرنده">
				@error('receiver')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-mobile-alt"></i>
					</div>
				</div>
				<input type="text" name="mobile" class="form-control @error('mobile') is-invalid @enderror" value="{{data('mobile', $data , $address)}}" placeholder="شماره همراه">
				@error('mobile')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-mobile-alt"></i>
					</div>
				</div>
				<input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{data('phone', $data , $address)}}" placeholder="تلفن ثابت">
				@error('phone')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-map-marker-alt"></i>
					</div>
				</div>
				<input type="text" name="state" class="form-control @error('state') is-invalid @enderror" value="{{data('state', $data , $address)}}" placeholder="استان">
				@error('state')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-map-marked"></i>
					</div>
				</div>
				<input type="text" name="city" class="form-control @error('city') is-invalid @enderror" value="{{data('city', $data , $address)}}" placeholder="شهر">
				@error('city')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-street-view"></i>
					</div>
				</div>
				<input type="text" name="address" class="form-control @error('address') is-invalid @enderror" value="{{data('address', $data , $address)}}" placeholder="آدرس گیرنده">
				@error('address')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-barcode-read"></i>
					</div>
				</div>
				<input type="text" name="postCode" class="form-control @error('postCode') is-invalid @enderror" value="{{data('postCode', $data , $address)}}" placeholder="کد پستی">
				@error('postCode')
				<span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
				@enderror                                        </div>
		</div>
		<div class="form-group bmd-form-group">
			<div class="input-group">
				<div class="input-group-prepend">
					<div class="input-group-text">
						<i class="fal fa-text-width" style="margin-bottom: auto;margin-top: 5px"></i>
					</div>
				</div>
				<textarea class="form-control" name="description" rows="3" placeholder="توضیحات اضافه" id="des">{{data('description', $data , $address)}}</textarea>

			</div>
		</div>
	</div>
	<div class="modal-footer justify-content-center">
		<button type="submit" class="btn pro-frm-btn px-4">ثبت آدرس</button>
		<button class="btn pro-frm-btn px-4">انصراف</button>
	</div>

</form>

Project/resources/views/App/Profile/EditPersonalinfo.blade.php
<?php
$user= Auth::user();
function userData(string $filed ){
    $user= Auth::user();
    if(old($filed) == null)
    {
        return $user->$filed;
    }
    return old($filed);
}
?>

@extends('Layouts.App.Profile')
@section('profile-content')
    <div class="title-products text-right">
        <h3 class="pro-title fs-18 dastnevis header-gradient d-inline-block pl-4 pl-md-4 pr-2 mb-0 mt-0 pb-2">
            <a href="" class="px-2">
                <i class="fal fa-arrow-right"></i>
            </a>
            ویرایش اطلاعات شخصی </h3>
        <hr class="under-title">
    </div>
    <div class="pbox bg-ff bx-sh px-3 py-3">
        <form method="post" action="{{route('profile.updateUser')}}">
            @csrf
            {{method_field('PATCH')}}
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">نام</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{userData('name')}}" >
                @error('name')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">نام خانوادگی</label>
                <input type="text" class="form-control @error('lastName') is-invalid @enderror" name="lastName" value="{{userData('lastName')}}">
                @error('lastName')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">کد ملی</label>
                <input type="text" class="form-control @error('nationalCode') is-invalid @enderror" name="nationalCode" value="{{userData('nationalCode')}}">
                @error('nationalCode')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">شماره کارت</label>
                <input type="text" name="cardNumber" class="form-control @error('cardNumber') is-invalid @enderror" value="{{userData('cardNumber')}}">
                @error('cardNumber')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">شماره موبایل</label>
                <input type="text" class="form-control @error('mobile') is-invalid @enderror" name="mobile" value="{{userData('mobile')}}">
                @error('mobile')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-4">
                <label class="text-right bmd-label-floating">پست الکترونیک</label>
                <input type="email" class="form-control text-left @error('email') is-invalid @enderror" name="email" value="{{userData('email')}}">
                @error('email')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-check py-2">
                <label class="form-check-label">
                    عضویت در خبرنامه هنرچی
                    <input class="form-check-input @error('newsletter') is-invalid @enderror" type="checkbox" {{$user->newsletter === 1 ? 'checked':""}}>
                    <span class="form-check-sign">
				              <span class="check"></span>
				          </span>
                </label>
                @error('newsletter')
                <span class="invalid-feedback" role="alert" style="text-align: right">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group bmd-form-group my-2 text-left my-3">
                <button type="submit" class="btn pro-frm-btn">ثبت اطلاعات کاربر</button>

                  <button type="reset" class="btn pro-frm-btn">انصراف</button>


            </div>
        </form>
    </div>

@endsection

Project/resources/views/App/Profile/Profile.blade.php
@extends('Layouts.App.Profile')
@section('profile-content')

  @include('Components.App.Profile.Personal-Information')
  @include('Components.App.Profile.latest-favorite')


@endsection

Project/resources/views/App/Profile/Wishlist.blade.php
@extends('Layouts.App.Profile')
@section('profile-content')

        <div class="profile-box">
            <div class="title-products text-right">
                <h3 class="pro-title fs-18 dastnevis header-gradient d-inline-block px-4 px-md-4 mb-0 pb-2">لیست آخرین علاقه مندی ها</h3>
                <hr class="under-title">
            </div>
            <div class="pbox p-list-box bg-ff px-3 py-3">
                <div class="row text-center">
                    @foreach($products as $product)
                    <div class="col-lg-6 col-md-12 col-sm-12 my-1 my-md-0 my-lg-3">
                        <div class="wl-items bx-sh py-3">
                            <a href="">
                                <div class="wl-img bx-sh p-2 ml-3">
                                    <img src="images/accessory/01.png">
                                </div>
                                <div class="wl-txt text-right">
                                    <p class="wl-title clr-42">
                                        {{$product->name}}
                                    </p>
                                    <p class="wl-price clr-red">
                                        تومان
                                    </p>
                                </div>
                            </a>
                            <div class="wl-btn">
                                <a href="{{route('profile.like',$product)}}">
                                    <button class="clr-75">
                                        <i class="fal fa-trash-alt"></i>
                                    </button>

                            </div>
                        </div>

                    </div>
                    @endforeach
                </div>

                <div class="text-center py-3">
                    <nav>
                        <ul class="pagination justify-content-center">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1"> <i class="fal fa-chevron-right"></i> </a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"> <i class="fal fa-chevron-left"></i> </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>

@endsection